spring.application.name=keeply

# 1. Configuracion del Servidor 
# (Busca el puerto de Railway, si no existe, usa el 8080 en tu PC)
server.port=${PORT:8080}

# 2. Conexion a la Base de Datos (Hibrida: Railway / Local)
# Usamos mysql y el nuevo Driver que pusimos en el pom.xml
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3307}/${MYSQLDATABASE:keeply_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Configuracion de JPA (Para que cree las tablas solo)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. JWT Configuration
jwt.secret=MiClaveSecretaParaKeeplyJWTMuyLargaYSegura2026ProyectoTFG
jwt.expiration=86400000

# 5. API Keys externas (TODO: Añadir las claves cuando estén disponibles)
# The Movie Database (TMDB)
api.tmdb.key=4da0b85272e93bad0f8ebc6c66adf077

# Jikan API (Anime/Manga) - Puede funcionar sin key pero es recomendable tenerla
api.jikan.key=

# RAWG API (Videojuegos)
api.rawg.key=17750cffeece4d9caf24cb0d78f41c5f

# Google Books API (Libros/Cómics) - Puede funcionar sin key pero es mejor tenerla
api.google.books.key=AIzaSyC47MtFrXUeQ54brFJK4Yd5UqvjXGjWLxQ
